//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Document.Mgr.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocumentModelContainer : DbContext
    {
        public DocumentModelContainer()
            : base("name=DocumentModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfos { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TechType> TechTypes { get; set; }
        public virtual DbSet<Tech> Techs { get; set; }
        public virtual DbSet<LevelDescription> LevelDescriptions { get; set; }
        public virtual DbSet<R_UserInfo_Tech> R_UserInfo_Techs { get; set; }
        public virtual DbSet<Country> Countrys { get; set; }
        public virtual DbSet<City> Citys { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
    }
}
