//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Document.Mgr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_UserInfo_Tech
    {
        public int Id { get; set; }
        public int UserInfoId { get; set; }
        public int TechId { get; set; }
        public int LevelDescriptionId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual Tech Tech { get; set; }
        public virtual LevelDescription LevelDescription { get; set; }
    }
}
