//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Document.Mgr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Gender = 1;
            this.IsEnabled = true;
            this.Auth = 0;
            this.R_UserInfo_Tech = new HashSet<R_UserInfo_Tech>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short Gender { get; set; }
        public string Pwd { get; set; }
        public string Remark { get; set; }
        public System.DateTime HiredTime { get; set; }
        public bool IsAssigned { get; set; }
        public string Picture { get; set; }
        public string Email { get; set; }
        public string UID { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsEnabled { get; set; }
        public int RoleId { get; set; }
        public int PositionId { get; set; }
        public int GroupId { get; set; }
        public short Auth { get; set; }
    
        public virtual ICollection<R_UserInfo_Tech> R_UserInfo_Tech { get; set; }
        public virtual Role Role { get; set; }
        public virtual Position Position { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Group Group { get; set; }
    }
}
